### PR TITLE
Improve threads & fix to gkci

### PR DESCRIPTION
**Pull request by marco-2023**
Improved chunks limits in `compute_overlap`. Now chunks have the same number of elements.

Added small fixes needed for gkci.

### CODE REVIEW

**Comment by msricher** [comment]
Thanks, Marco. This logic is basically used everywhere (filling in the sparse_op, enpt2, etc.). Do you think we could abstract out the logic here and then put that into each of the threaded functions?

I can bring up the relevant sections by searching "chunksize" in the repo
https://github.com/search?q=repo%3Atheochem%2FPyCI%20chunksize&type=code

**Comment by msricher** [comment]
https://github.com/theochem/PyCI/blob/master/pyci/src/sparseop.cpp#L187

Also here, where the <i|H|j> elements are computed. I think I took out the threading entirely after having the problem with bad scheduling.

Let me know if I can help, or if you'd like me to do some of this myself.

**Review by RichRick1 — APPROVED** [review]

**Comment by marco-2023** [comment]
Thanks @msricher I will, do so.

**Comment by msricher** [comment]
OK, this looks good. I will add the threading back into the sparse_op soon, and then we can merge.

**Comment by marco-2023** [comment]
Thank you @msricher, I tried to do it, but there are parameters that I still do not know what they are (e.g. startrow), which makes it difficult for me. It will be more efficient if you do it.

**Pull request merged**
